CREATE TABLE fitness_user (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    user_pass TEXT NOT NULL,
    is_active BOOLEAN
);