CREATE TABLE IF NOT EXISTS fitness_workout (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    use_id INTEGER REFERENCES fitness_user(id),
    ex_id INTEGER REFERENCES fitness_exercise(id),
    set_number INTEGER,
    num_of_reps INTEGER,
    weight_used INTEGER,
    date_completed TIMESTAMPTZ DEFAULT now(),
    is_active BOOLEAN
);