CREATE TABLE IF NOT EXISTS workout (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    use_id INTEGER REFERENCES user(id) NOT NULL,
    ex_id INTEGER REFERENCES exercise(id) NOT NULL,
    set_number INTEGER,
    num_of_reps INTEGER,
    weight_used INTEGER,
    date_completed TIMESTAMPTZ DEFAULT now(),
    is_active BOOLEAN
);