DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS exercise;
DROP TABLE IF EXISTS workout;

CREATE TABLE IF NOT EXISTS user (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    user_pass TEXT NOT NULL,
    is_active BOOLEAN
);

CREATE TABLE IF NOT EXISTS exercise (
    exercise_id INTEGER PRIMARY KEY GENERATED BY DEFAULT,
    excercise_type TEXT,
    exercise_name TEXT NOT NULL,
    exercise_desc TEXT NOT NULL,
    is_active BOOLEAN
);

CREATE TABLE IF NOT EXISTS workout (
    workout_id INTEGER PRIMARY KEY GENERATED BY DEFAULT,
    user_id INTEGER REFERENCES user(user_id) NOT NULL,
    exercise_id INTEGER REFERENCES exercise(exercise_id) NOT NULL,
    set_number INTEGER,
    num_of_reps INTEGER,
    weight_used INTEGER,
    date_completed TIMESTAMP DEFAULT now(),
    is_active BOOLEAN
);