DROP TABLE IF EXISTS exercise;

CREATE TABLE IF NOT EXISTS exercise (
    exercise_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    excercise_type TEXT,
    exercise_name TEXT NOT NULL,
    exercise_desc TEXT NOT NULL,
    is_active BOOLEAN
);